### PR TITLE
Feature/arrows highlight

### PR DESCRIPTION
**Pull request by mathematicalmichael**
Issue:
(a) Arrows only point _towards_ tasks in pipelines, not _away_ from them, making it pretty hard to trace dependencies by-eye for large pipelines.
(b) Inconsistent arrow ordering (nondeterministic: `.sort((a, b) => a.selected && !b.selected ? 1 : -1)`)
(c) Colors of unselected arrows do not have sufficient contrast with selected ones.
(d) Default proxy port should reflect default API backend port.

Proposed Solution:
(a) Trace target + source in order to highlight both types of arrows.
(b) small change
(c) small change (opinionated choices made. If anything the choice of unselected color may be too dark now... need to try it on a variety of screens)
(d) small change

Demo:
unselected before:
image

unselected after:
image

selected before:
image

selected after:
image

another example:
this output arrow was basically impossible to identify before: 
image

image

so I can actually find the task associated with its destination

image

given that the rows are deterministic right now, I could technically highlight outgoing and incoming _with the same color_, but when there are a lot of arrows coming in or out, it becomes easier to tell which are input vs output if the colors differ.

The new "outgoing arrow" color is the old "unselected color" and the new "unselected color" is darker.

Feedback would be welcome / appreciated.

### CODE REVIEW

**Comment by mathematicalmichael** [comment]
i changed the types to both be `number` but let me know if it's preferred to treat them both as `string` instead.

**Review by shyallegro — CHANGES_REQUESTED** [review]
first of all thank you , this is a great idea.
I've showed this change to our UX/UI designer and he asked for some changes.

1.  when no step is selected we should use the current arrow color, we do that by adding a class next to `.arrows` like `[class.selected]="..."`
2. with selection, he suggested we use $blue-600 for other arrows, $blue-200 for selected and $blue-300 for outgoing

image

**Comment by mathematicalmichael** [comment]
pushed the change for (2), and for (1) there is already
image
so I'm awaiting clarification if that's not correct. Since we're on different time zones, feel free to push the change for that.

**Comment by mathematicalmichael** [comment]
PS I've never seen this terminal icon on a step before... what is it?
image

**Comment by shyallegro** [comment]
Hi, the idea in 1 was to differentiate when no step is selected, and keep all arrows the same color as before, to a state where a step is selected, for this case we can dim the other arrows but not as much as you did, see the color I specified.
we can use a conditional class in line 27 `[class.selected]="..."` than handle the 2 different state in the SCSS file

`.arrows {
    &.selected {
      ...new color scheme
    }
    ... old color scheme
`

the icon is for type training, not sure if this is due to a very old example I have in the server

**Comment by mathematicalmichael** [comment]
ah I see.
I honestly don't even know what I just did in that last commit but it seems to have had the intended effect.

nothing selected: prior default color
image
something selected: new dark background
image
good suggestion.

and I meant the icon on the right side, looks like a "terminal prompt" icon. I've seen the task types, but yeah... best i can tell tasks dont have icons on the right anymore. =)

**Review by shyallegro — APPROVED** [review]

**Pull request merged**
