### PR TITLE
github action for testing builds

### PR DESCRIPTION
**Pull request by mathematicalmichael**
I put in PR #82 but wanted a way to get feedback on the build process, so I added CI.

had to add `--legacy-peer-deps` bc `npm ci` threw the following:

```
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: @ngneat/dag@2.0.0
npm error Found: @angular/platform-browser-dynamic@17.3.7
npm error node_modules/@angular/platform-browser-dynamic
npm error   @angular/platform-browser-dynamic@"^17.3.7" from the root project
npm error
npm error Could not resolve dependency:
npm error peer @angular/platform-browser-dynamic@"13.3.5" from @ngneat/dag@2.0.0
npm error node_modules/@ngneat/dag
npm error   @ngneat/dag@"^2.0.0" from the root project
npm error
npm error Conflicting peer dependency: @angular/platform-browser-dynamic@13.3.5
npm error node_modules/@angular/platform-browser-dynamic
npm error   peer @angular/platform-browser-dynamic@"13.3.5" from @ngneat/dag@2.0.0
npm error   node_modules/@ngneat/dag
npm error     @ngneat/dag@"^2.0.0" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /home/runner/.npm/_logs/2024-06-27T21_36_33_667Z-eresolve-report.txt
```

Let me know if I should also update the README to add the required flag.

### CODE REVIEW

**Comment by shyallegro** [comment]
that's strange, we have a `.nprc` with legacy-peer-deps, I'd expect it to take effect on any environment

**Comment by mathematicalmichael** [comment]
> seems we forgot to push the `.nprc` file with legacy-peer-deps, which handle this issue

would you like me to modify the action to remove that flag? or just close this out entirely?

**Comment by shyallegro** [comment]
@mathematicalmichael the actions is a good idea, i'll push the .npmrc  file, so you can remove the flag

**Comment by mathematicalmichael** [comment]
I rebased from your branch and removed the irrelevant commits to keep history clean / enable fast-fwd merges.

**Review by shyallegro — APPROVED** [review]

**Pull request merged**
